spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pokemo}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:pokemo}
    password: ${DB_PASSWORD:pokemo}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.pokemo: DEBUG
